@url = http://127.0.0.1:8080/generos
GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "nome" : "Policial"
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "id" : 0,
    "nome" : "Terror"
}

###
DELETE {{url}}/1